name: mdat-auth Deployment to S3 and CloudFront

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      - run: pnpm build

      - run: |
          aws s3 cp ./dist/index.html s3://$AWS_BUCKET_NAME/index.html \
            --cache-control no-store \
            --content-type text/html

      - run: |
          find ./dist/assets -name "*.js" | while read file; do
            aws s3 cp "$file" "s3://$AWS_BUCKET_NAME/assets/$(basename "$file")" \
              --cache-control "public, max-age=31536000, immutable" \
              --content-type application/javascript
          done

      - run: |
          find ./dist/assets -name "*.css" | while read file; do
            aws s3 cp "$file" "s3://$AWS_BUCKET_NAME/assets/$(basename "$file")" \
              --cache-control "public, max-age=31536000, immutable" \
              --content-type text/css
          done

      - run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"
